name: mce_irl_experiments
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - absl-py=2.3.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.11.18
  - aiosignal=1.3.2
  - ale-py=0.10.2
  - alsa-lib=1.2.14
  - aom=3.9.1
  - astroid=3.3.9
  - asttokens=2.4.1
  - async-timeout=5.0.1
  - attr=2.5.1
  - attrs=25.3.0
  - av=14.2.0
  - backports=1.0
  - backports.tarfile=1.2.0
  - box2d-py=2.3.8
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cairo=1.18.4
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.1
  - cpython=3.10.17
  - cuda-crt-tools=12.9.41
  - cuda-cudart=12.9.37
  - cuda-cudart_linux-64=12.9.37
  - cuda-cuobjdump=12.9.26
  - cuda-cupti=12.9.19
  - cuda-nvcc-tools=12.9.41
  - cuda-nvdisasm=12.9.19
  - cuda-nvrtc=12.9.41
  - cuda-nvtx=12.9.19
  - cuda-nvvm-tools=12.9.41
  - cuda-version=12.9
  - cudnn=9.10.1.4
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.8.1
  - decorator=5.1.1
  - dill=0.3.9
  - double-conversion=3.3.1
  - exceptiongroup=1.3.0
  - executing=2.0.1
  - expat=2.7.0
  - faker=25.8.0
  - farama-notifications=0.0.4
  - ffmpeg=7.1.1
  - filelock=3.18.0
  - fluidsynth=2.3.7
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.51.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozenlist=1.6.0
  - fsspec=2025.3.2
  - gdk-pixbuf=2.42.12
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.13
  - grpcio=1.71.0
  - gym=0.26.1
  - gym-notices=0.0.8
  - gymnasium=1.0.0
  - h2=4.2.0
  - harfbuzz=11.2.1
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imageio=2.37.0
  - imageio-ffmpeg=0.6.0
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=6.29.4
  - ipython=8.25.0
  - isort=6.0.1
  - jack=1.9.22
  - jaraco.context=6.0.1
  - jax-jumpy=1.0.0
  - jedi=0.19.1
  - jinja2=3.1.6
  - joblib=1.5.0
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - level-zero=1.22.3
  - libabseil=20250127.1
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libass=0.17.3
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.75
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.6
  - libclang13=20.1.6
  - libcublas=12.9.0.13
  - libcudnn=9.10.1.4
  - libcudnn-dev=9.10.1.4
  - libcudss=0.5.0.16
  - libcufft=11.4.0.6
  - libcufile=1.14.0.30
  - libcups=2.3.3
  - libcurand=10.3.10.19
  - libcusolver=11.7.4.40
  - libcusparse=12.5.9.5
  - libdeflate=1.24
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libexpat=2.7.0
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.1
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgpg-error=1.55
  - libgrpc=1.71.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.6
  - liblzma=5.8.1
  - libmad=0.15.1b
  - libmagma=2.9.0
  - libnl=3.11.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvjitlink=12.9.41
  - libogg=1.3.5
  - libopengl=1.7.0
  - libopenvino=2025.0.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-intel-cpu-plugin=2025.0.0
  - libopenvino-intel-gpu-plugin=2025.0.0
  - libopenvino-intel-npu-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.5
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - librsvg=2.58.4
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.50.0
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.4
  - libtiff=4.7.0
  - libtorch=2.7.0
  - libudev1=257.4
  - libunwind=1.6.2
  - liburing=2.9
  - libusb=1.0.28
  - libuuid=2.38.1
  - libuv=1.51.0
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvm-openmp=20.1.6
  - lz4-c=1.10.0
  - markdown=3.8
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - matplotlib-inline=0.1.7
  - mccabe=0.7.0
  - mdurl=0.1.2
  - mkl=2024.2.2
  - moviepy=1.0.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - multidict=6.4.3
  - munkres=1.1.4
  - nccl=2.26.6.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numpy=1.26.4
  - ocl-icd=2.3.3
  - opencl-headers=2024.10.24
  - openh264=2.6.0
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.5.0
  - optree=0.16.0
  - opusfile=0.12
  - packaging=24.2
  - pandas=2.2.2
  - pango=1.56.3
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=25.1.1
  - pixman=0.46.0
  - platformdirs=4.2.2
  - portaudio=19.6.0
  - portmidi=2.0.4
  - proglog=0.1.10
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - propcache=0.3.1
  - protobuf=5.29.3
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pygame=2.6.1
  - pygments=2.18.0
  - pylint=3.3.6
  - pyparsing=2.4.7
  - pyside6=6.9.0
  - pysocks=1.7.1
  - python=3.10.17
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch=2.7.0
  - pytz=2024.1
  - pywin32=306
  - pyzmq=26.0.3
  - qhull=2020.2
  - qt6-main=6.9.0
  - rav1e=0.7.1
  - rdma-core=57.0
  - re2=2024.07.02
  - readline=8.2
  - requests=2.32.3
  - rich=14.0.0
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - sdl2=2.32.54
  - sdl2_image=2.8.2
  - sdl2_mixer=2.6.3
  - sdl2_ttf=2.24.0
  - sdl3=3.2.14
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.8.2
  - six=1.16.0
  - sleef=3.8
  - snappy=1.2.1
  - stable-baselines3=2.6.0
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - svt-av1=3.0.2
  - swig=4.3.0
  - sympy=1.14.0
  - tbb=2021.13.0
  - tensorboard=2.19.0
  - tensorboard-data-server=0.7.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tomli=2.2.1
  - tomlkit=0.13.2
  - tornado=6.4.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - triton=3.3.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.4.0
  - wayland=1.23.1
  - wayland-protocols=1.44
  - wcwidth=0.2.13
  - werkzeug=3.1.3
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yarl=1.20.0
  - zeromq=4.3.5
  - zipp=3.22.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - minigrid==3.0.0
prefix: /mnt/data/rebeccaw00dm/miniforge3/envs/mce_irl_experiments
